### PR TITLE
Today's work

### PR DESCRIPTION
**Pull request by ngawangtrinley**
@shugtso please review

### CODE REVIEW

**Review by shugtso — CHANGES_REQUESTED** [review]
@ngawang
Can you please recheck the file, most of them are same.

**Review by shugtso — CHANGES_REQUESTED** [review]
Please select more image.

**Comment by ngawangtrinley** [comment]
> Please select more image.

Why should I add more images?

**Comment by shugtso** [comment]
because it is less than 100

**Pull request merged**
